apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: authorization-api-pdb
  namespace: {{ .Values.projectName }}
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      service: authorization-api
