{{- if ne .Values.observability.logging_stack "LEGACY" }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: clickhouse-pdb
  namespace: {{ .Values.projectName }}
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      service: clickhouse
{{- end }}