apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: engine-tiny-pdb
  namespace: {{ .Values.projectName }}
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      service: engine-tiny