{{- if and (ne .Values.observability.logging_stack "LEGACY") .Values.observability.exporters.prometheus.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prometheus-pdb
  namespace: {{ .Values.projectName }}
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      service: prometheus
{{- end }}