apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: storage-api-pdb
  namespace: {{ .Values.projectName }}
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      service: storage-api
