apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: studio-ray-worker-pdb
  namespace: {{ .Values.projectName }}
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      service: studio-ray-worker
