{{- if .Values.services.secretsGenerator.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: snorkelflow-secrets-generator-cr
  namespace: {{ .Values.projectName }}
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - create
  - patch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: snorkelflow-secrets-generator-sa
  namespace: {{ .Values.projectName }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name:  snorkelflow-secrets-generator-cr
  namespace: {{ .Values.projectName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: snorkelflow-secrets-generator-cr
subjects:
- kind: ServiceAccount
  name: snorkelflow-secrets-generator-sa
  namespace: {{ .Values.projectName }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: snorkelflow-secrets-generator-{{ randAlphaNum 5 | lower }}
  namespace: {{ .Values.projectName }}
spec:
  template:
    spec:
      containers:
      - args:
        - generate-secrets
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: LOGGING_STACK
          value: {{ .Values.observability.logging_stack }}
        - name: SNORKELFLOW_HOSTNAME
          value: {{ .Values.traffic.ingresses.services.snorkelflow.urlPrefix }}.{{ .Values.traffic.ingresses.domain }}
        - name: SNORKEL_FLOW_VERSION
          value: "{{ .Values.version }}"
        {{- if .Values.image.imageNames.singleuserNotebook }}
        - name: SINGLEUSER_NOTEBOOK_BASE_IMAGE_NAME
          value: {{ .Values.image.imageNames.singleuserNotebook }}
        {{- end }}
        {{- if .Values.image.imageNames.secretsGenerator }}
        image: {{ .Values.image.imageNames.secretsGenerator }}
        {{- else }}
        image: {{ template "snorkelflow.registryPrefix" . }}snorkelai/secrets-generator:{{ .Values.version }}
        {{- end }}
        name: generate-secrets
      imagePullSecrets:
      - name: {{ .Values.image.imagePullSecret | default "regcred" }}
      restartPolicy: Never
      securityContext:
        fsGroup: 99
        runAsUser: 99
        runAsNonRoot: true
      serviceAccountName: snorkelflow-secrets-generator-sa
{{- end }}
