{{- $images := .Files.Get "images.json" | fromJson }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    always-pinned: "0"
    service: influxdb
    project: {{ .Values.projectName }}
    snorkel.ai/compute-type: cpu
{{- if or .Values.services.influxdb.labels .Values.services.labels }}
{{ toYaml (merge .Values.services.influxdb.labels .Values.services.labels) | indent 4 }}
{{- end }}
  name: influxdb
  namespace: {{ .Values.projectName }}
spec:
  strategy:
    type: Recreate
  replicas: 1
{{- if .Values.services.progressDeadlineSeconds }}
  progressDeadlineSeconds: {{ .Values.services.progressDeadlineSeconds }}
{{- end }}
  selector:
    matchLabels:
      service: influxdb
      project: {{ .Values.projectName }}
  template:
    metadata:
      labels:
        always-pinned: "0"
        service: influxdb
        project: {{ .Values.projectName }}
        snorkel.ai/compute-type: cpu
{{- if or .Values.services.influxdb.labels .Values.services.labels }}
{{ toYaml (merge .Values.services.influxdb.labels .Values.services.labels) | indent 8 }}
{{- end }}
    spec:
{{- if or .Values.affinity.binPackAlwaysPinnedPods .Values.affinity.nodeAffinity }}
      affinity:
        {{- if .Values.affinity.binPackAlwaysPinnedPods }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: always-pinned
                operator: In
                values:
                - "1"
            topologyKey: kubernetes.io/hostname
            namespaceSelector: {}
        {{- end }}
        {{- with .Values.affinity.nodeAffinity }}
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- end }}
      {{- with .Values.affinity.nodeSelectors }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecret | default "regcred" }}
      securityContext:
        fsGroup: 99
        runAsUser: 99
      serviceAccountName: snorkelflow-sa
      containers:
      - env:
        - name: SERVICE_TYPE
          value: influxdb
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: TELEGRAF_CADVISOR_URL
          value: telegraf:8186
{{- range $k, $v := (merge .Values.services.influxdb.env .Values.services.env) }}
        - name: {{ $k }}
          value: {{ $v | toString | quote }}
{{- end }}
        {{- if .Values.image.imageNames.influxdb }}
        image: {{ .Values.image.imageNames.influxdb }}
        {{- else }}
        image: {{ template "snorkelflow.registryPrefix" . }}{{ $images.docker_hub_repo }}/{{ get $images.custom_images "influxdb" }}
        {{- end }}
        name: influxdb
        {{- if .Values.services.influxdb.containerSecurityContext }}
        securityContext:
          {{- toYaml .Values.services.influxdb.containerSecurityContext | nindent 10 }}
        {{- end }}
        args:
          - influxd
          - --reporting-disabled
          - --bolt-path=/var/opt/.influxdbv2/influxd.bolt
          - --engine-path=/var/opt/.influxdbv2/engine
        ports:
          - containerPort: 8086
        volumeMounts:
        - mountPath: /var/opt/.influxdbv2
          name: influxdb
        resources:
{{- if .Values.services.influxdb.resources }}
{{ toYaml .Values.services.influxdb.resources | indent 10 }}
{{- else }}
          requests:
            memory: 4.0Gi
            cpu: "2.0"
          limits:
            memory: 4.0Gi
            cpu: "2.0"
{{- end }}
        readinessProbe:
          httpGet:
            path: /health
            port: 8086
          initialDelaySeconds: 3
          periodSeconds: 30
        startupProbe:
          httpGet:
            path: /health
            port: 8086
          periodSeconds: 30
          failureThreshold: 120
        livenessProbe:
          httpGet:
            path: /health
            port: 8086
          periodSeconds: 30
      volumes:
      - name: influxdb
        persistentVolumeClaim:
          claimName: {{ .Values.projectName }}-influxdb
