{{- if not .Values.services.jupyterhub.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    always-pinned: "0"
    service: notebook
    project: {{ .Values.projectName }}
    {{- if .Values.gpu.enabled }}
    snorkel.ai/compute-type: gpu
    {{- else }}
    snorkel.ai/compute-type: cpu
    {{- end }}
{{- if or .Values.services.notebook.labels .Values.services.labels }}
{{ toYaml (merge .Values.services.notebook.labels .Values.services.labels) | indent 4 }}
{{- end }}
  name: notebook
  namespace: {{ .Values.projectName }}
spec:
  strategy:
    type: Recreate
{{- if .Values.services.jupyterhub.enabled }}
  replicas: 0
{{- else }}
  replicas: 1
{{- end }}
{{- if .Values.services.progressDeadlineSeconds }}
  progressDeadlineSeconds: {{ .Values.services.progressDeadlineSeconds }}
{{- end }}
  selector:
    matchLabels:
      service: notebook
      project: {{ .Values.projectName }}
  template:
    metadata:
      labels:
        always-pinned: "0"
        service: notebook
        project: {{ .Values.projectName }}
        {{- if .Values.gpu.enabled }}
        snorkel.ai/compute-type: gpu
        {{- else }}
        snorkel.ai/compute-type: cpu
        {{- end }}
{{- if or .Values.services.notebook.labels .Values.services.labels}}
{{ toYaml (merge .Values.services.notebook.labels .Values.services.labels) | indent 8 }}
{{- end }}
    spec:
{{- if or .Values.affinity.binPackAlwaysPinnedPods .Values.affinity.nodeAffinity }}
      affinity:
        {{- if .Values.affinity.binPackAlwaysPinnedPods }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: always-pinned
                operator: In
                values:
                - "1"
            topologyKey: kubernetes.io/hostname
            namespaceSelector: {}
        {{- end }}
        {{- if not .Values.gpu.enabled }}
        {{- with .Values.affinity.nodeAffinity }}
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- end }}
{{- end }}
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecret | default "regcred" }}
      securityContext:
        runAsUser: 99
        fsGroup: 99
      serviceAccountName: snorkelflow-sa
      {{- if and .Values.gpu.enabled .Values.gpu.gpu_config }}
      {{- if .Values.gpu.gpu_config.node_selectors }}
      nodeSelector:
        {{- range $key, $value := .Values.gpu.gpu_config.node_selectors }}
        {{ $key }}: "{{ $value }}"
        {{- end }}
      {{- end }}
      {{- if .Values.gpu.gpu_config.schedulerName }}
      schedulerName: {{ .Values.gpu.gpu_config.schedulerName }}
      {{- end }}
      {{- if .Values.gpu.gpu_config.tolerations }}
      {{- with .Values.gpu.gpu_config.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
{{- else }}
  {{- if .Values.affinity.nodeSelectors }}
    {{- with .Values.affinity.nodeSelectors }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  {{- end }}
  {{- if .Values.affinity.tolerations }}
    {{- with .Values.affinity.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  {{- end }}
{{- end }}
      containers:
      - env:
        - name: SERVICE_TYPE
          value: notebook
        - name: IS_GPU_ENABLED
          value: "1"
        - name: TORNADO_HOST_IP
          value: {{ .Values.traffic.ingresses.services.snorkelflow.urlPrefix }}.{{ .Values.traffic.ingresses.domain }}
        - name: USE_ASYNC_JUPYTER_KERNEL_MANAGER
          value: "0"
        - name: NOTEBOOK_IP
          value: {{ .Values.traffic.ingresses.services.snorkelflow.urlPrefix }}-notebook.{{ .Values.traffic.ingresses.domain }}
        - name: NOTEBOOK_PORT
          value: "80"
        - name: NOTEBOOK_TLS_PORT
          value: "443"
        - name: NOTEBOOK_BASE_URL
          value: /notebook/
        - name: SNORKELFLOW_API_KEY
          value: {{ default "36380ba0-965b-44f6-95c5-01dc7a8ec608" .Values.services.notebook.notebookApiKey }}
        - name: HOME
{{- if .Values.services.jupyterhub.enabled }}
          value: /data
{{- else }}
          value: /data/.snorkel-flow-notebooks
{{- end }}
        - name: SSO_HOST_IP
          value: {{ .Values.traffic.ingresses.services.snorkelflow.urlPrefix }}.{{ .Values.traffic.ingresses.domain }}
        - name: SNORKELFLOW_MOUNT_DIR
          value: /data
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: TDM_API_URL
          value: http://tdm-api:8686
        - name: STORAGE_API_URL
          value: http://storage-api:31315
        - name: MINIO_URL
          value: http://minio:9001
        - name: STUDIO_API_URL
          value: http://studio-api:8484
        - name: TELEGRAF_CADVISOR_URL
          value: telegraf:8186
        - name: TELEGRAF_URL
          value: http://telegraf:8125
{{- if .Values.services.notebook.secretsFromFile }}
        - name: MINIO_ACCESS_KEY_FILE
          value: /etc/secrets/minio-secret/minio_access_key
        - name: MINIO_SECRET_KEY_FILE
          value: /etc/secrets/minio-secret/minio_secret_key
{{- else }}
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: minio_access_key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: minio_secret_key
{{- end }}
{{- range $k, $v := (merge .Values.services.notebook.env .Values.services.env) }}
        - name: {{ $k }}
          value: {{ $v | toString | quote }}
{{- end }}
        {{- if .Values.image.imageNames.notebook }}
        image: {{ .Values.image.imageNames.notebook }}
        {{- else if .Values.gpu.enabled }}
        image: {{ template "snorkelflow.registryPrefix" . }}snorkelai/notebook:{{ .Values.version }}-cuda
        {{- else }}
        image: {{ template "snorkelflow.registryPrefix" . }}snorkelai/notebook:{{ .Values.version }}
        {{- end }}
        {{- if .Values.image.imagePullPolicy }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        {{- end }}
        name: notebook
        {{- if .Values.services.notebook.containerSecurityContext }}
        securityContext:
          {{- toYaml .Values.services.notebook.containerSecurityContext | nindent 10 }}
        {{- end }}
        args:
        - notebook
        - --host
        - 0.0.0.0
        ports:
        - containerPort: 8888
        - containerPort: 8282
        volumeMounts:
        - mountPath: /tmp
          name: empty-dir
          subPath: tmp-dir
        - mountPath: /var/log
          name: empty-dir
          subPath: log-dir
        - mountPath: /data
          name: data
        - mountPath: /etc/auth/jwt
          name: jwt-key-pub
{{- if .Values.services.notebook.secretsFromFile }}
        - name: minio-secret-volume
          mountPath: /etc/secrets/minio-secret
          readOnly: true
{{- end }}
        resources:
{{- if .Values.services.notebook.resources }}
{{ toYaml .Values.services.notebook.resources | indent 10 }}
{{- else }}
          requests:
            memory: 32.0Gi
            cpu: "8.0"
            {{- if .Values.gpu.enabled }}
            nvidia.com/gpu: '1'
            {{- end }}
          limits:
            memory: 32.0Gi
            cpu: "8.0"
            {{- if .Values.gpu.enabled }}
            nvidia.com/gpu: '1'
            {{- end }}
{{- end }}
      volumes:
      - name: empty-dir
        emptyDir: {}
      - name: data
        persistentVolumeClaim:
          claimName: {{ template "snorkelflow.pvcName" . }}
      - name: jwt-key-pub
        secret:
          secretName: jwt-key-pub
{{- if .Values.services.notebook.secretsFromFile }}
      - name: minio-secret-volume
        secret:
          secretName: minio-secret
{{- end }}
{{- end }}
