{{- $envOverrides := merge .Values.services.studioRayWorker.env .Values.services.env }}
{{- $images := .Files.Get "images.json" | fromJson }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    always-pinned: "0"
    service: studio-ray-worker
    project: {{ .Values.projectName }}
    snorkel.ai/compute-type: cpu
    snorkel.ai/ray-cluster-name: studio-ray-cluster
{{- if or .Values.services.studioRayWorker.labels .Values.services.labels }}
{{ toYaml (merge .Values.services.studioRayWorker.labels .Values.services.labels) | indent 4 }}
{{- end }}
  name: studio-ray-worker
  namespace: {{ .Values.projectName }}
spec:
  strategy:
    type: Recreate
{{- if .Values.services.studioRayWorker.replicas }}
  replicas: {{ .Values.services.studioRayWorker.replicas }}
{{- else }}
  replicas: 1
{{- end }}
{{- if .Values.services.progressDeadlineSeconds }}
  progressDeadlineSeconds: {{ .Values.services.progressDeadlineSeconds }}
{{- end }}
  selector:
    matchLabels:
      service: studio-ray-worker
      project: {{ .Values.projectName }}
  template:
    metadata:
      labels:
        always-pinned: "0"
        service: studio-ray-worker
        project: {{ .Values.projectName }}
        snorkel.ai/compute-type: cpu
        snorkel.ai/ray-cluster-name: studio-ray-cluster
{{- if or .Values.services.studioRayWorker.labels .Values.services.labels }}
{{ toYaml (merge .Values.services.studioRayWorker.labels .Values.services.labels) | indent 8 }}
{{- end }}
    spec:
{{- if or .Values.affinity.binPackAlwaysPinnedPods .Values.affinity.nodeAffinity }}
      affinity:
        {{- if .Values.affinity.binPackAlwaysPinnedPods }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: always-pinned
                operator: In
                values:
                - "1"
            topologyKey: kubernetes.io/hostname
            namespaceSelector: {}
        {{- end }}
        {{- with .Values.affinity.nodeAffinity }}
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- end }}
      {{- with .Values.affinity.nodeSelectors }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecret | default "regcred" }}
      securityContext:
        runAsUser: 99
        fsGroup: 99
      serviceAccountName: snorkelflow-sa
      containers:
        - env:
            - name: SERVICE_TYPE
              value: studio-ray-worker
            - name: HF_HOME
              value: "/tmp/snorkel-pretrained-models"
            - name: SNORKEL_FLOW_VERSION
              value: "config_test"
            - name: SSO_HOST_IP
              value: snorkelflow.snorkel-ai.com
            - name: ENABLE_PRETRAINED_MODEL_DIRECTORY
              value: {{ .Values.pretrained_models.enabled | toString | title | quote }}
            - name: ARROW_CACHE_ENABLED
              value: {{ if .Values.optimizations.arrow_cache.enabled }}"1"{{ else }}"0"{{ end }}
            - name: LD_PRELOAD
              value: /usr/lib/x86_64-linux-gnu/libjemalloc.so.2
            - name: MALLOC_CONF
              value: background_thread:true
            - name: MALLOC_MMAP_THRESHOLD_
              value: "16384"
            - name: STUDIO_RAY_ENABLED
              value: "1"
{{- if not (hasKey $envOverrides "STUDIO_RAY_WORKER_CPU_COUNT") }}
            - name: STUDIO_RAY_WORKER_CPU_COUNT
              value: "8"
{{- end }}
{{- if not (hasKey $envOverrides "STUDIO_RAY_WORKER_MEMORY_GB") }}
            - name: STUDIO_RAY_WORKER_MEMORY_GB
              value: "32"
{{- end }}
{{- if not (hasKey $envOverrides "STUDIO_RAY_INTERACTIVE_SHARED_CPU_COUNT") }}
            - name: STUDIO_RAY_INTERACTIVE_SHARED_CPU_COUNT
              value: "4"
{{- end }}
{{- if not (hasKey $envOverrides "STUDIO_RAY_INTERACTIVE_SHARED_MEMORY_GB") }}
            - name: STUDIO_RAY_INTERACTIVE_SHARED_MEMORY_GB
              value: "16"
{{- end }}
            - name: STUDIO_RAY_HEAD_REDIS_PORT
              value: "7380"
            - name: CUPY_CACHE_DIR
              value: /var/lib/snorkel/.cupy-cache
            - name: LOGGING_STACK
              value: {{ .Values.observability.logging_stack }}
            - name: SNORKELFLOW_MOUNT_DIR
              value: /data
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: REDIS_URL
              value: redis
            - name: MINIO_URL
              value: http://minio:9001
            - name: TELEGRAF_CADVISOR_URL
              value: telegraf:8186
            - name: TELEGRAF_URL
              value: http://telegraf:8125
{{- if .Values.services.studioRayWorker.secretsFromFile }}
            - name: TDM_CONN_STR_FILE
              value: /etc/secrets/db-secret/tdm_conn_str
{{- else }}
            - name: TDM_CONN_STR
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: tdm_conn_str
{{- end }}
            - name: STUDIO_RAY_HEAD_URL
              value: ray://studio-ray-head:10002
            - name: STUDIO_API_URL
              value: http://studio-api:8484
{{- if .Values.services.studioRayWorker.secretsFromFile }}
            - name: MINIO_ACCESS_KEY_FILE
              value: /etc/secrets/minio-secret/minio_access_key
            - name: MINIO_SECRET_KEY_FILE
              value: /etc/secrets/minio-secret/minio_secret_key
            {{- if .Values.influx_cloud_key }}
            - name: INFLUXDB_CLOUD_TOKEN_G498_FILE
              value: /etc/secrets/influxdb-cloud-secret/influxdb_cloud_token
            {{- end }}
{{- else }}
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: minio_access_key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: minio_secret_key
            {{- if .Values.influx_cloud_key }}
            - name: INFLUXDB_CLOUD_TOKEN_G498
              valueFrom:
                secretKeyRef:
                  name: influxdb-cloud-secret
                  key: influxdb_cloud_token
            {{- end }}
{{- end }}
{{- if and .Values.traffic.istio.enabled ((.Values.traffic.istio).mtls).enabled }}
            - name: IS_ISTIO_STRICT_MTLS_ENABLED
              value: "True"
{{- end }}
{{- with include "launchDarkly.envVars" . }}
{{ . | indent 12 }}
{{- end }}
{{- range $k, $v := $envOverrides }}
            - name: {{ $k }}
              value: {{ $v | toString | quote }}
{{- end }}
          {{- if .Values.image.imageNames.studio }}
          image: {{ .Values.image.imageNames.studio }}
          {{- else if .Values.gpu.enabled }}
          image: {{ template "snorkelflow.registryPrefix" . }}snorkelai/studio-api:{{ .Values.version }}-cuda
          {{- else }}
          image: {{ template "snorkelflow.registryPrefix" . }}snorkelai/studio-api:{{ .Values.version }}
          {{- end }}
          {{- if .Values.image.imagePullPolicy }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          {{- end }}
          name: studio-ray-worker
          {{- if .Values.services.studioRayWorker.containerSecurityContext }}
          securityContext:
            {{- toYaml .Values.services.studioRayWorker.containerSecurityContext | nindent 12 }}
          {{- end }}
          args:
            - ray-worker
            - --ray-head-address=studio-ray-head
            - --ray-head-port=7380
            - --ray-head-client-port=10002
          ports: []
          volumeMounts:
            - mountPath: /tmp
              name: empty-dir
              subPath: tmp-dir
            - mountPath: /var/log
              name: empty-dir
              subPath: log-dir
            - mountPath: /data
              name: data
            - mountPath: /etc/auth/jwt
              name: jwt-key-pub
            - mountPath: /dev/shm
              name: dshm
{{- if .Values.services.studioRayWorker.secretsFromFile }}
            - name: minio-secret-volume
              mountPath: /etc/secrets/minio-secret
              readOnly: true
            - name: db-secret-volume
              mountPath: /etc/secrets/db-secret
              readOnly: true
            {{- if .Values.influx_cloud_key }}
            - name: influxdb-cloud-secret-volume
              mountPath: /etc/secrets/influxdb-cloud-secret
              readOnly: true
            {{- end }}
{{- end }}
{{- with include "logging.mounts" (deepCopy . | merge (dict "service_type" "studio-ray-worker")) }}
{{ . | indent 12 }}
{{- end }}
          resources:
{{- if .Values.services.studioRayWorker.resources }}
{{ toYaml .Values.services.studioRayWorker.resources | indent 12 }}
{{- else }}
            requests:
              memory: 32.0Gi
              cpu: "8.0"
            limits:
              memory: 32.0Gi
              cpu: "8.0"
{{- end }}
{{- with include "logging.sidecar" (deepCopy . | merge (dict "service_type" "studio-ray-worker")) }}
{{ . | indent 8 }}
{{- end }}
      volumes:
        - name: empty-dir
          emptyDir: {}
        - name: data
          persistentVolumeClaim:
            claimName: {{ template "snorkelflow.pvcName" . }}
        - name: jwt-key-pub
          secret:
            secretName: jwt-key-pub
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 10000Mi
{{- if .Values.services.studioRayWorker.secretsFromFile }}
        - name: minio-secret-volume
          secret:
            secretName: minio-secret
        - name: db-secret-volume
          secret:
            secretName: db-secret
        {{- if .Values.influx_cloud_key }}
        - name: influxdb-cloud-secret-volume
          secret:
            secretName: influxdb-cloud-secret
        {{- end }}
{{- end}}
{{- with include "logging.volumes" (deepCopy . | merge (dict "service_type" "studio-ray-worker")) }}
{{ . | indent 8 }}
{{- end }}