{{- if ne .Values.observability.logging_stack "LEGACY" }}
apiVersion: v1
data:
  "0.txt": |-
    CREATE DATABASE IF NOT EXISTS logs;
    CREATE TABLE IF NOT EXISTS logs.snorkelflow (timestamp DateTime64(4, 'UTC'), service String, level String, log String, host String) ENGINE = MergeTree() ORDER BY (timestamp, service, level);
    ALTER TABLE logs.snorkelflow MODIFY TTL toDateTime(timestamp) + INTERVAL 7 DAY DELETE WHERE level = 'info', toDateTime(timestamp) + INTERVAL 14 DAY DELETE WHERE level != 'info';
kind: ConfigMap
metadata:
  name: clickhouse-migrations-config-map
  namespace: {{ .Values.projectName }}
{{- end }}
