{{- if ne .Values.observability.logging_stack "LEGACY" }}
apiVersion: v1
data:
  base.xml: |-
    <clickhouse>
        <listen_host>::</listen_host>
        <listen_host>0.0.0.0</listen_host>
        <listen_try>1</listen_try>

        <access_control_improvements>
            <settings_constraints_replace_previous>true</settings_constraints_replace_previous>
        </access_control_improvements>

        <logger>
            <level>information</level>
            <log>/var/log/clickhouse-server/clickhouse-server-%F-%T.log</log>
            <errorlog>/var/log/clickhouse-server/clickhouse-server-%F-%T.err.log</errorlog>
            <size>100M</size>
            <count>1</count>
            <formatting>
                <type>json</type>
                <names>
                    <date_time>date_time</date_time>
                    <thread_name>thread_name</thread_name>
                    <thread_id>thread_id</thread_id>
                    <level>level</level>
                    <query_id>query_id</query_id>
                    <logger_name>logger_name</logger_name>
                    <message>message</message>
                    <source_file>source_file</source_file>
                    <source_line>source_line</source_line>
                </names>
            </formatting>
        </logger>
    </clickhouse>
kind: ConfigMap
metadata:
  name: clickhouse-config-config-map
  namespace: {{ .Values.projectName }}
{{- end }}
