apiVersion: v1
data:
  grafana.ini: |
    instance_name = "{{ .Values.traffic.ingresses.services.snorkelflow.urlPrefix }}.{{ .Values.traffic.ingresses.domain }}"

    [security]
{{- if .Values.services.grafana.secretsFromFile }}
    admin_user = $__file{/etc/secrets/grafana-secret/grafana_admin_username}
    admin_password = $__file{/etc/secrets/grafana-secret/grafana_admin_password}
{{- else }}
    admin_user = "${GRAFANA_ADMIN_USERNAME}"
    admin_password = "${GRAFANA_ADMIN_PASSWORD}"
{{- end }}
    angular_support_enabled = false

    [server]
    http_port = 3000
{{- if .Values.traffic.basePath }}
    root_url = "http://{{ .Values.traffic.ingresses.services.snorkelflow.urlPrefix }}.{{ .Values.traffic.ingresses.domain }}{{.Values.traffic.basePath}}/grafana/"
{{- else }}
    root_url = "http://{{ .Values.traffic.ingresses.services.snorkelflow.urlPrefix }}.{{ .Values.traffic.ingresses.domain }}/grafana/"
{{- end }}
    serve_from_sub_path = true

    [unified_alerting]
    enabled = true

    [metrics]
    enabled = false
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: {{ .Values.projectName }}
