{{- if ne .Values.observability.logging_stack "LEGACY" }}
apiVersion: v1
data:
  get-secrets: |-
    #!/bin/sh

    input=$(jq -r . /dev/stdin)
    output="{}"

    clickhouse_username() {
        CLICKHOUSE_USERNAME=$(cat ${CLICKHOUSE_USER_FILE})
        result="{\"$1\": {\"value\" : \"${CLICKHOUSE_USERNAME}\", \"error\": null}}"
        output=$(echo "$output $result" | jq -c '. + input')
    }

    clickhouse_password() {
        CLICKHOUSE_PASSWORD=$(cat ${CLICKHOUSE_PASSWORD_FILE})
        result="{\"$1\": {\"value\" : \"${CLICKHOUSE_PASSWORD}\", \"error\": null}}"
        output=$(echo "$output $result" | jq -c '. + input')
    }

    datadog_api_key() {
        DD_API_KEY=$(cat ${DD_API_KEY_FILE})
        result="{\"$1\": {\"value\" : \"${DD_API_KEY}\", \"error\": null}}"
        output=$(echo "$output $result" | jq -c '. + input')
    }

    datadog_site() {
        DD_SITE=$(cat ${DD_SITE_FILE})
        result="{\"$1\": {\"value\" : \"${DD_SITE}\", \"error\": null}}"
        output=$(echo "$output $result" | jq -c '. + input')
    }

    prometheus_username() {
        PROMETHEUS_USERNAME=$(cat ${PROMETHEUS_USER_FILE})
        result="{\"$1\": {\"value\" : \"${PROMETHEUS_USERNAME}\", \"error\": null}}"
        output=$(echo "$output $result" | jq -c '. + input')
    }

    prometheus_password() {
        PROMETHEUS_PASSWORD=$(cat ${PROMETHEUS_PASSWORD_FILE})
        result="{\"$1\": {\"value\" : \"${PROMETHEUS_PASSWORD}\", \"error\": null}}"
        output=$(echo "$output $result" | jq -c '. + input')
    }

    for secret in $(echo ${input} | jq -r '.secrets[]'); do
        if [ "${secret}" = "clickhouse_username" ]; then
            clickhouse_username "${secret}"
        elif [ "${secret}" = "clickhouse_password" ]; then
            clickhouse_password "${secret}"
        elif [ "${secret}" = "datadog_api_key" ]; then
            datadog_api_key "${secret}"
        elif [ "${secret}" = "datadog_site" ]; then
            datadog_site "${secret}"
        elif [ "${secret}" = "prometheus_username" ]; then
            prometheus_username "${secret}"
        elif [ "${secret}" = "prometheus_password" ]; then
            prometheus_password "${secret}"
        fi
    done
    echo -n "${output}"
kind: ConfigMap
metadata:
  name: vector-helpers-config-map
  namespace: {{ .Values.projectName }}
{{- end }}
