{{- if and (ne .Values.observability.logging_stack "LEGACY") .Values.volumes.prometheus.persistentVolume.enabled .Values.observability.exporters.prometheus.enabled  }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.projectName }}-prometheus-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: {{ .Values.volumes.prometheus.storageRequest }}
{{- if .Values.volumes.prometheus.persistentVolume.driver }}
{{ toYaml .Values.volumes.prometheus.persistentVolume.driver | indent 2 }}
{{- end }}
  storageClassName: {{ .Values.volumes.prometheus.storageClass }}
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
{{- end }}