{{- if not .Values.services.secretsGenerator.enabled }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.projectName }}
  name: db-prefect-secret
type: Opaque
data:
  prefect_db_conn_url: cG9zdGdyZXNxbCthc3luY3BnOi8vcG9zdGdyZXM6cG9zdGdyZXNAZGI6NTQzMi9wcmVmZWN0
{{- end }}