{{- if and (not .Values.services.secretsGenerator.enabled) .Values.services.jupyterhub.enabled }}
apiVersion: v1
data:
{{- range $path, $_ := .Files.Glob "notebooks/**" }}
  {{ base $path }}: !!binary |
{{ $.Files.Get $path | b64enc | b64enc | indent 4 }}
{{- end }}
kind: Secret
metadata:
  name: jupyterhub-singleuser-shared-secret
  namespace: {{ .Values.projectName }}
type: Opaque
{{- end }}