{{- if and (ne .Values.observability.logging_stack "LEGACY") .Values.traffic.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: clickhouse-network-policy
  namespace: {{ .Values.projectName }}
spec:
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
    to: []
{{- if .Values.traffic.allowInternetAccess}}
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 192.168.0.0/16
        - 172.16.0.0/20
{{- end }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: grafana
    ports:
    - port: 9000
  - from:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: vector
    ports:
    - port: 8123
  podSelector:
    matchLabels:
      project: {{ .Values.projectName }}
      service: clickhouse
  policyTypes:
  - Ingress
  - Egress
{{- end }}