{{- if .Values.traffic.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: flow-ui-network-policy
  namespace: {{ .Values.projectName }}
spec:
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
    to: []
{{- if .Values.traffic.allowInternetAccess}}
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 192.168.0.0/16
        - 172.16.0.0/20
{{- end }}
  - ports:
    - port: 8484
    to:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: studio-api
  - ports:
    - port: 8686
    to:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: tdm-api
  - ports:
    - port: 8186
    - port: 8125
      protocol: UDP
    to:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: telegraf
  - ports:
    - port: 8086
    to:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: influxdb
{{- if ne .Values.observability.logging_stack "LEGACY" }}
  - to:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: vector
    ports:
    - port: 6000
{{- end }}
  ingress:
{{- if .Values.traffic.allowAllInboundTrafficOnKeyServices}}
  - from: []
    ports:
    - port: 5000
{{- end}}
{{- range $rule := .Values.traffic.networkPolicies.ingresses }}
  - from:
{{ toYaml $rule.from | indent 4}}
    ports:
      port: 5000
{{- end }}
  - from:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: envoy-front-proxy
    ports:
    - port: 5000
  podSelector:
    matchLabels:
      project: {{ .Values.projectName }}
      service: flow-ui
  policyTypes:
  - Ingress
  - Egress
{{- end }}
