{{- if .Values.traffic.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: influxdb-network-policy
  namespace: {{ .Values.projectName }}
spec:
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
    to: []
  - ports:
    - port: 8186
    to:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: telegraf
  ingress:
{{- if .Values.traffic.allowAllInboundTrafficOnKeyServices}}
  - from: []
    ports:
    - port: 8086
{{- end}}
{{- range $rule := .Values.traffic.networkPolicies.ingresses }}
  - from:
{{ toYaml $rule.from | indent 4}}
    ports:
      port: 8086
{{- end }}
  - from:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: flow-ui
    ports:
    - port: 8086
  - from:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: tdm-api
    ports:
    - port: 8086
  - from:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: engine
    ports:
    - port: 8086
  - from:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: telegraf
    ports:
    - port: 8086
  - from:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: grafana
    ports:
    - port: 8086
  podSelector:
    matchLabels:
      project: {{ .Values.projectName }}
      service: influxdb
  policyTypes:
  - Ingress
  - Egress
{{- end }}
