{{- if .Values.traffic.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: storage-api-network-policy
  namespace: {{ .Values.projectName }}
spec:
  podSelector:
    matchLabels:
      project: {{ .Values.projectName }}
      service: storage-api
  policyTypes:
  - Ingress
  - Egress
  ingress:
{{- if not .Values.services.jupyterhub.enabled }}
  - from:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: notebook
    ports:
    - port: 31315
{{- end }}
  - from:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: envoy-front-proxy
    ports:
    - port: 31315
  - from:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: ray-worker
    ports:
    - port: 31315
{{- if and .Values.gpu.enabled (ne (.Values.services.rayGpuWorker.max_replicas | toString) "0") }}
  - from:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: ray-gpu-worker
    ports:
    - port: 31315
{{- end }}
{{- if .Values.services.jupyterhub.enabled }}
  - from:
    - podSelector:
        matchLabels:
          app: jupyterhub
          component: singleuser-server
          release: jupyterhub
    ports:
    - port: 31315
{{- end }}
  egress:
  - to: []
    # Allow DNS resolution
    ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  - to:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: tdm-api
    ports:
    - port: 8686
  - to:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: authorization-api
    ports:
    - port: 31314
  - to:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: redis
    ports:
    - port: 6379
  - to:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: telegraf
    ports:
    - port: 8186
    - port: 8125
      protocol: UDP
  - to:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: db
    ports:
    - port: 5432
{{- if ne .Values.observability.logging_stack "LEGACY" }}
  - to:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: vector
    ports:
    - port: 6000
{{- end }}
{{- end }}
