{{- if .Values.traffic.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: studio-api-network-policy
  namespace: {{ .Values.projectName }}
spec:
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
    to: []
{{- if .Values.traffic.allowInternetAccess}}
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 192.168.0.0/16
        - 172.16.0.0/20
{{- end }}
  - ports:
    - port: 8686
    to:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: tdm-api
  - ports:
    - port: 5432
    to:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: db
  - ports:
    - port: 31314
    to:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: authorization-api
  - ports:
    - port: 6379
    to:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: redis
  - ports:
    {{- if .Values.services.minio.ui.enabled }}
    - port: 9000
    {{- end }}
    - port: 9001
    to:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: minio
  - ports:
    - port: 8186
    - port: 8125
      protocol: UDP
    to:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: telegraf
  - ports: []
    to:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: studio-ray-head
  - ports: []
    to:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: studio-ray-worker
{{- if ne .Values.observability.logging_stack "LEGACY" }}
  - to:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: vector
    ports:
    - port: 6000
{{- end }}
  ingress:
{{- if .Values.traffic.allowAllInboundTrafficOnKeyServices}}
  - from: []
    ports:
    - port: 8484
{{- end}}
  - from:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: flow-ui
    ports:
    - port: 8484
{{- if not .Values.services.jupyterhub.enabled }}
  - from:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: notebook
    ports:
    - port: 8484
{{- end }}
  - from:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: envoy-front-proxy
    ports:
    - port: 8484
  - from:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: studio-ray-worker
    ports:
    - port: 8484
  - from:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: studio-ray-head
    ports:
    - port: 8484
{{- range $rule := .Values.traffic.networkPolicies.ingresses }}
  - from:
{{ toYaml $rule.from | indent 4}}
    ports:
      port: 8484
{{- end }}
{{- if .Values.services.jupyterhub.enabled }}
  - from:
    - podSelector:
        matchLabels:
          project: {{ .Values.projectName }}
          service: jupyterhub
    ports:
    - port: 8484
  - from:
    - podSelector:
        matchLabels:
          app: jupyterhub
          component: singleuser-server
          release: jupyterhub
    ports:
    - port: 8484
{{- end }}
  podSelector:
    matchLabels:
      project: {{ .Values.projectName }}
      service: studio-api
  policyTypes:
  - Ingress
  - Egress
{{- end }}
