{{- if .Values.services.jupyterhub.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    project: {{ .Values.projectName }}
    service: jupyterhub
  name: jupyterhub
  namespace: {{ .Values.projectName }}
spec:
  ports:
  - name: '8081'
    port: 8081
    targetPort: 8081
  selector:
    service: jupyterhub
  type: {{ .Values.traffic.ingresses.serviceType }}
{{- end }}