apiVersion: v1
kind: Service
metadata:
  labels:
    service: minio
    project: {{ .Values.projectName }}
  name: minio
  namespace: {{ .Values.projectName }}
spec:
  type: {{ .Values.traffic.ingresses.serviceType }}
  ports:
{{- if .Values.services.minio.ui.enabled }}
  - name: "9000"
    port: 9000
    targetPort: 9000
{{- end }}
  - name: "9001"
    port: 9001
    targetPort: 9001
  selector:
    service: minio
