{{- if not .Values.services.jupyterhub.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    service: notebook
    project: {{ .Values.projectName }}
  name: notebook
  namespace: {{ .Values.projectName }}
spec:
  type: {{ .Values.traffic.ingresses.serviceType }}
  ports:
  - name: "8888"
    port: 8888
    targetPort: 8888
  - name: "8282"
    port: 8282
    targetPort: 8282
  selector:
    service: notebook
{{- end }}