apiVersion: v1
kind: Service
metadata:
  labels:
    project: {{ .Values.projectName }}
    service: studio-ray-head
  name: studio-ray-head
  namespace: {{ .Values.projectName }}
spec:
  ports:
  - name: '7380'
    port: 7380
    targetPort: 7380
  - name: '8266'
    port: 8266
    targetPort: 8266
  - name: '10002'
    port: 10002
    targetPort: 10002
  selector:
    service: studio-ray-head
  type: {{ .Values.traffic.ingresses.serviceType }}
