{
 "title": "Autoscaling Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Kubernetes PodDisruptionBudget - Max Unavailable",
   "type": "graph",
   "description": "Displays the current PodDisruptionBudget setting that is applied globally to all deployments in OVERNIGHT_UNPINNED_DEPLOYMENTS, all other deployments are always pinned (e.g. max unavalable is set to 0). Setting max unavailable to 1 means pods can be moved to different nodes to enable binpacking, setting it to 0 pins it to the node it's currently running on.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"autoscaler_pdb_max_unavailable\")\n    |> filter(fn: (r) => r[\"_field\"] == \"value\")\n    |> group(columns: [\"_measurement\"])\n    |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Time Since Deployment Activity",
   "type": "graph",
   "description": "For each of the worker deployments, displays amount of time that has elapsed since there were any new activity in any of the queues the worker follows",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"autoscaler_deployment_time_since_activity\")\n    |> filter(fn: (r) => r[\"_field\"] == \"mean\")\n    |> group(columns: [\"deployment\"])\n    |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Engine RQ Worker Autoscaling",
   "type": "graph",
   "description": "For the 'Engine RQ' workers, displays the replica limit and the counts of both the desired replicas (requested by autoscaler) and the active replicas (running in k8s)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"autoscaler_deployment_active_replicas\" or r[\"_measurement\"] == \"autoscaler_deployment_desired_replicas\" or r[\"_measurement\"] == \"autoscaler_deployment_replica_limit\")\n    |> filter(fn: (r) => r[\"deployment\"] =~ /engine/)\n    |> filter(fn: (r) => r[\"_field\"] == \"value\")\n    |> group(columns: [\"_measurement\", \"deployment\"])\n    |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Model Trainer RQ Worker Autoscaling",
   "type": "graph",
   "description": "For the 'Model Trainer RQ' workers, displays the replica limit and the counts of both the desired replicas (requested by autoscaler) and the active replicas (running in k8s)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"autoscaler_deployment_active_replicas\" or r[\"_measurement\"] == \"autoscaler_deployment_desired_replicas\" or r[\"_measurement\"] == \"autoscaler_deployment_replica_limit\")\n    |> filter(fn: (r) => r[\"deployment\"] =~ /model-trainer/)\n    |> filter(fn: (r) => r[\"_field\"] == \"value\")\n    |> group(columns: [\"_measurement\", \"deployment\"])\n    |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Engine Ray Worker Autoscaling",
   "type": "graph",
   "description": "For the 'Engine Ray' workers, displays the replica limit and the counts of both the desired replicas (requested by autoscaler) and the active replicas (running in k8s)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"autoscaler_deployment_active_replicas\" or r[\"_measurement\"] == \"autoscaler_deployment_desired_replicas\" or r[\"_measurement\"] == \"autoscaler_deployment_replica_limit\")\n    |> filter(fn: (r) => r[\"deployment\"] =~ /ray-(gpu-)?worker/)\n    |> filter(fn: (r) => r[\"_field\"] == \"value\")\n    |> group(columns: [\"_measurement\", \"deployment\"])\n    |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Autoscaler Health",
   "type": "graph",
   "description": "For each of the autoscaled deployments, displays the diff (desired - active) of the replica counts, and alerts if the discrepancy is > 0 or < 0 for an extended period of time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "active_replicas = from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"autoscaler_deployment_active_replicas\")\n\ndesired_replicas = from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"autoscaler_deployment_desired_replicas\")\n\nactive_desired_joined = join(\n    tables: {\n        active_replicas:active_replicas,\n        desired_replicas:desired_replicas\n    },\n    on: [\"_time\", \"deployment\"]\n)\n\nactive_desired_joined\n    |> map(fn: (r) => ({\n        r with\n        _value: int(v: r._value_desired_replicas - r._value_active_replicas)\n        }))\n    |> keep(columns: [\"_time\", \"_value\", \"deployment\"])\n    |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  }
 ]
}