{
 "title": "Caching",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Cache Hits and Misses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"tdm_cache_hit\" or r[\"_measurement\"] == \"tdm_cache_miss\")\n    |> aggregateWindow(every: v.windowPeriod, fn: sum)\n    |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Number of Redis Keys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"redis_keyspace\")\n    |> filter(fn: (r) => r[\"_field\"] == \"keys\")\n    |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n    |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"redis\")\n    |> filter(fn: (r) => r[\"_field\"] == \"clients\")\n    |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n    |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"redis\")\n    |> filter(fn: (r) => r[\"_field\"] == \"used_memory_peak\" or r[\"_field\"] == \"used_memory\" or r[\"_field\"] == \"used_memory_rss\")\n    |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n    |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Feature Store Metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] =~ /^feature_store_.+/)\n    |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n    |> yield(name: \"sum\")"
    }
   ]
  }
 ]
}