{
 "title": "DB",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Number of DB Queries from TDM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"tdm_db_num_queries\")\n    |> filter(fn: (r) => r[\"_field\"] == \"value\")\n    |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n    |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Num db queries from engine",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"engine_db_num_queries\")\n    |> filter(fn: (r) => r[\"_field\"] == \"value\")\n    |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n    |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Num db queries from studio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"studio_db_num_queries\")\n    |> filter(fn: (r) => r[\"_field\"] == \"value\")\n    |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n    |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Studio connection pool Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"studio_db_connection_pool_available\" or r[\"_measurement\"] == \"studio_db_connection_pool_total\" or r[\"_measurement\"] == \"studio_db_connection_pool_used\")\n    |> filter(fn: (r) => r[\"_field\"] == \"value\")\n    |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n    |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "TDM connection pool Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"tdm_db_connection_pool_available\" or r[\"_measurement\"] == \"tdm_db_connection_pool_total\" or r[\"_measurement\"] == \"tdm_db_connection_pool_used\")\n    |> filter(fn: (r) => r[\"_field\"] == \"value\")\n    |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n    |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Number of Active Backend Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n    |> filter(fn: (r) => r[\"_field\"] == \"numbackends\")\n    |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n    |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Connection acquisition time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"db_pool_acquire_time\")\n    |> filter(fn: (r) => r[\"_field\"] == \"100_percentile\")\n    |> group(columns: [\"service\", \"_time\"])\n    |> max()\n    |> group(columns: [\"service\"])\n    |> keep(columns: [\"service\", \"_value\", \"_time\"])\n    |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n    |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Connection release time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"db_pool_connection_time\")\n    |> filter(fn: (r) => r[\"_field\"] == \"100_percentile\")\n    |> group(columns: [\"service\", \"_time\"])\n    |> max()\n    |> group(columns: [\"service\"])\n    |> keep(columns: [\"service\", \"_value\", \"_time\"])\n    |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n    |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Dead locks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n    |> filter(fn: (r) => r[\"_field\"] == \"deadlocks\")\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Number of Rows returned",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n    |> filter(fn: (r) => r[\"_field\"] == \"tup_returned\")\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Rows Inserted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n    |> filter(fn: (r) => r[\"_field\"] == \"tup_inserted\")\n    |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n    |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Rows Fetched",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n    |> filter(fn: (r) => r[\"_field\"] == \"tup_fetched\")\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Transactions Rolledback",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n    |> filter(fn: (r) => r[\"_field\"] == \"xact_rollback\")\n    |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n    |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Disk Blks Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n    |> filter(fn: (r) => r[\"_field\"] == \"blks_read\" or r[\"_field\"] == \"blks_hit\")\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Transactions Commited",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n    |> filter(fn: (r) => r[\"_field\"] == \"xact_commit\")\n    |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n    |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Rows deleted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n    |> filter(fn: (r) => r[\"_field\"] == \"tup_deleted\")\n    |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n    |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Number of Bytes written to temp file",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n    |> filter(fn: (r) => r[\"_field\"] == \"temp_bytes\")\n    |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n    |> yield(name: \"max\")"
    }
   ]
  }
 ]
}