{
 "title": "Endpoint Performance",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "P100 Latency Under 10000 Millis - Flow UI",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"api_requests_latency\")\n    |> filter(fn: (r) => r[\"_field\"] == \"100_percentile\")\n    |> filter(fn: (r) => r._value < 10000)\n    |> filter(fn: (r) => r.api_name == \"Flow UI\")\n    |> map(fn: (r) => ({\n            path: r.api_name + \": \" + r.method + \" \" + r.path + \" \" + r.status_code,\n            _time: r._time,\n            _value: r._value\n        }))"
    }
   ]
  },
  {
   "title": "P100 Latency over 10000 Millis - Flow UI",
   "type": "table",
   "description": "All requests to Flow UI that took longer than the cutoff.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n   |> filter(fn: (r) => r[\"_measurement\"] == \"api_requests_latency\")\n   |> filter(fn: (r) => r[\"_field\"] == \"100_percentile\")\n   |> filter(fn: (r) => r._value > 10000)\n   |> filter(fn: (r) => r.api_name == \"Flow UI\")\n   |> map(fn: (r) => ({\n           _path: r.api_name + \": \" + r.method + \" \" + r.path + \" \" + r.status_code,\n           _time: r._time,\n           _value: r._value\n       }))"
    }
   ]
  },
  {
   "title": "P100 Latency Under 10000 Millis - Snorkel TDM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"api_requests_latency\")\n    |> filter(fn: (r) => r[\"_field\"] == \"100_percentile\")\n    |> filter(fn: (r) => r._value < 10000)\n    |> filter(fn: (r) => r.api_name == \"Snorkel TDM\")\n    |> map(fn: (r) => ({\n            path: r.api_name + \": \" + r.method + \" \" + r.path + \" \" + r.status_code,\n            _time: r._time,\n            _value: r._value\n        }))"
    }
   ]
  },
  {
   "title": "P100 Latency over 10000 Millis - Snorkel TDM",
   "type": "table",
   "description": "All requests to Snorkel TDM that took longer than the cutoff.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n   |> filter(fn: (r) => r[\"_measurement\"] == \"api_requests_latency\")\n   |> filter(fn: (r) => r[\"_field\"] == \"100_percentile\")\n   |> filter(fn: (r) => r._value > 10000)\n   |> filter(fn: (r) => r.api_name == \"Snorkel TDM\")\n   |> map(fn: (r) => ({\n           _path: r.api_name + \": \" + r.method + \" \" + r.path + \" \" + r.status_code,\n           _time: r._time,\n           _value: r._value\n       }))"
    }
   ]
  },
  {
   "title": "P100 Latency Under 10000 Millis - Studio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"api_requests_latency\")\n    |> filter(fn: (r) => r[\"_field\"] == \"100_percentile\")\n    |> filter(fn: (r) => r._value < 10000)\n    |> filter(fn: (r) => r.api_name == \"Studio\")\n    |> map(fn: (r) => ({\n            path: r.api_name + \": \" + r.method + \" \" + r.path + \" \" + r.status_code,\n            _time: r._time,\n            _value: r._value\n        }))"
    }
   ]
  },
  {
   "title": "P100 Latency over 10000 Millis - Studio",
   "type": "table",
   "description": "All requests to Studio that took longer than the cutoff.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n   |> filter(fn: (r) => r[\"_measurement\"] == \"api_requests_latency\")\n   |> filter(fn: (r) => r[\"_field\"] == \"100_percentile\")\n   |> filter(fn: (r) => r._value > 10000)\n   |> filter(fn: (r) => r.api_name == \"Studio\")\n   |> map(fn: (r) => ({\n           _path: r.api_name + \": \" + r.method + \" \" + r.path + \" \" + r.status_code,\n           _time: r._time,\n           _value: r._value\n       }))"
    }
   ]
  }
 ]
}