{
 "title": "Engine Latency",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Train model job steps 90th percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n    |> filter(fn: (r) => r[\"event_type\"] =~ /^(get_clarity_matrix.*)|(ingest_predictions.*)|(load_data_from_config.*)|(train_predict.*)$/)\n    |> filter(fn: (r) => r._measurement == \"engine_task_latency\")\n    |> filter(fn: (r) => r._field == \"90_percentile\")"
    }
   ]
  },
  {
   "title": "Transfer assets 90th percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n    |> filter(fn: (r) => r[\"event_type\"] =~ /^transfer_assets.*$/)\n    |> filter(fn: (r) => r._measurement == \"engine_task_latency\")\n    |> filter(fn: (r) => r._field == \"90_percentile\")"
    }
   ]
  },
  {
   "title": "Job component latency 90th percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"engine_task_latency\")\n    |> filter(fn: (r) => r._field == \"90_percentile\")"
    }
   ]
  },
  {
   "title": "Engine components latency 99th percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"engine_task_latency\")\n    |> filter(fn: (r) => r._field == \"99_percentile\")"
    }
   ]
  },
  {
   "title": "Engine components latency 100th percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"engine_task_latency\")\n    |> filter(fn: (r) => r._field == \"100_percentile\")"
    }
   ]
  }
 ]
}