{
 "title": "RQ",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Health of Queue",
   "type": "graph",
   "description": "Fraction of workers that are healthy per-queue. This should be 100% almost all of the time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"rq_worker_healthy\")\n    |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\n    |> group(columns: [\"_time\", \"queue\"])\n    |> mean()\n    |> group(columns: [\"queue\"])"
    }
   ]
  },
  {
   "title": "Pending Queue Size",
   "type": "graph",
   "description": "Number of jobs waiting in queue. This should be zero most of the time. Extended period of non-zero values indicate jobs are spending significant amounts of time waiting for an RQ worker",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"rq_queue_pending\")\n    |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n    |> group(columns: [\"_time\", \"queue\"])\n    |> sum()\n    |> group(columns: [\"queue\"])\n    |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Healthy workers per-queue",
   "type": "graph",
   "description": "Number of healthy workers per-queue.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"rq_worker_healthy\")\n    |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\n    |> group(columns: [\"_time\", \"queue\"])\n    |> sum()\n    |> group(columns: [\"queue\"])\n    |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Worker utilization per-queue",
   "type": "graph",
   "description": "Fraction of workers actively working on a job. If any queue is capped at 100%, indicates the queue is under-resourced.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"rq_worker_busy\")\n    |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n    |> group(columns: [\"_time\", \"queue\"])\n    |> mean()\n    |> group(columns: [\"queue\"])\n    |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Worker Last Heartbeat",
   "type": "graph",
   "description": "Last time a RQ worker sent a heartbeat. Helps find unresponsive workers.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"rq_worker_last_heartbeat_sec\")\n    |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n    |> keep(columns: [\"_time\", \"_value\", \"hostname\", \"worker\"])\n    |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Current Job Execution",
   "type": "graph",
   "description": "Worker time spent on current job, if worker has job",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"rq_worker_job_execution_time\")\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> keep(columns: [\"_time\", \"hostname\", \"worker\", \"_value\"])\n    |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}