{
 "title": "Studio Ray Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Interactive Shared Worker Expected Heap Utilization Percentage (RSS - SHR)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interactive_shared_worker_heap_utilization_percentage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Interactive Shared Speedup Multiple Over Dask",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interactive_shared_speedup_multiple\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Interactive Shared Speedup Seconds Over Dask",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interactive_shared_speedup_seconds\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Dask LF apply latency vs Ray LF apply latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r[\"_measurement\"] == \"interactive_shared_dask_seconds\" or r[\"_measurement\"] == \"interactive_shared_ray_seconds\")\n|> filter(fn: (r) => r[\"_field\"] == \"value\")\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n|> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Number of UserNodeActors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"UserNodeActor_count\")\n    |> filter(fn: (r) => r[\"_field\"] == \"value\")\n    |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n    |> aggregateWindow(every: 1m, fn: max, createEmpty: false)\n    |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "UserNodeActor Total Memory Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"UserNodeActor_memory_gb\")\n    |> filter(fn: (r) => r[\"_field\"] == \"value\")\n    |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n    |> aggregateWindow(every: 1m, fn: max, createEmpty: false)\n    |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Ray Tasks by State",
   "type": "graph",
   "description": "Shows current ray tasks in different states",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"ray_scheduler_tasks\" and r[\"State\"] != \"SpilledUnschedulable\" and r[\"State\"] != \"SpilledWaiting\")\n    |> filter(fn: (r) => r[\"hostname\"] =~ /^studio-ray-head.*/)\n    |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n    |> group(columns: [\"_time\", \"State\"])\n    |> sum()\n    |> group(columns: [\"State\"])"
    }
   ]
  },
  {
   "title": "Unschedulable Tasks By Reason",
   "type": "graph",
   "description": "Shows tasks that are currently pending and why",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"ray_scheduler_unscheduleable_tasks\")\n    |> filter(fn: (r) => r[\"hostname\"] =~ /^studio-ray-head.*/)\n    |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n    |> group(columns: [\"_time\", \"Reason\"])\n    |> sum()\n    |> group(columns: [\"Reason\"])"
    }
   ]
  },
  {
   "title": "Spilled Objects by Count",
   "type": "graph",
   "description": "Spilled objects by count/state",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"ray_spill_manager_objects\")\n    |> filter(fn: (r) => r[\"hostname\"] =~ /^studio-ray-head.*/)\n    |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n    |> group(columns: [\"_time\", \"State\"])\n    |> sum()\n    |> group(columns: [\"State\"])"
    }
   ]
  },
  {
   "title": "Spilled Objects by Size",
   "type": "graph",
   "description": "Spilled objects by size/state",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"ray_spill_manager_objects_bytes\")\n    |> filter(fn: (r) => r[\"hostname\"] =~ /^studio-ray-head.*/)\n    |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n    |> group(columns: [\"_time\", \"State\"])\n    |> sum()\n    |> group(columns: [\"State\"])"
    }
   ]
  },
  {
   "title": "Unintentional worker failures",
   "type": "graph",
   "description": "Number of worker failures that are not intentional. For example, worker failures due to system related errors\nIf \"Data does not have a time field\" shows up, there have been no errors in the time range.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "import \"experimental/aggregate\"\nfrom(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"ray_unintentional_worker_failures_total\")\n    |> filter(fn: (r) => r[\"hostname\"] =~ /^studio-ray-head.*/)\n    |> aggregate.rate(\n        every: 1m,\n        unit: 1m,\n    )\n    |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: true)"
    }
   ]
  },
  {
   "title": "Task failures due to worker startup failure",
   "type": "graph",
   "description": "Number of tasks that fail to be scheduled because workers were not available.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"ray_scheduler_failed_worker_startup_total\")\n    |> filter(fn: (r) => r[\"hostname\"] =~ /^studio-ray-head.*/)\n    |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n    |> keep(columns: [\"_time\", \"Reason\", \"hostname\", \"_value\"])"
    }
   ]
  }
 ]
}