{
 "title": "System Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Disk Usage on Important Mounts",
   "type": "graph",
   "description": "All mounts matching /dev/*, not including overlay mounts.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"machine\"] =~ /^(tdm-api|db|influxdb)/)\n    |> filter(fn: (r) => r[\"_field\"] == \"value\")\n    |> filter(fn: (r) => r[\"device\"] =~ /\\/dev(\\/(xvda|nvme).*)$/)\n    |> filter(fn: (r) => r._measurement =~ /fs_(usage|limit)/ )\n    |> keep(columns: [\"device\", \"_time\", \"_value\", \"machine\", \"type\", \"_field\"])\n    |> aggregateWindow(every: 1m, fn: mean)\n    |> sort(columns: [\"_time\"])\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"type\"], valueColumn: \"_value\")\n    |> map(fn: (r) => ({ r with _value: r.usage / r.limit * 100.0, _measurement: \"FS %\" }))\n    |> keep(columns: [\"device\", \"_time\", \"_value\", \"machine\"])"
    }
   ]
  },
  {
   "title": "Service Memory RSS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"memory_rss\")\n    |> group(columns: [\"machine\"])\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Service CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_total\")\n    |> keep(columns: [\"_time\", \"_value\", \"machine\"])\n    |> aggregateWindow(every: 30s, fn: last, createEmpty: false)\n    |> derivative(nonNegative: true)\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> toFloat()\n    |> map(fn: (r) => ({\n        r with\n        _value: r._value / 10000000.0\n        })\n    )\n    |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"per_process_disk_io_read_bytes\")\n    |> aggregateWindow(every: 30s, fn: last, createEmpty: false)\n    |> derivative(nonNegative: true)\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> group(columns: [\"hostname\", \"_time\"])\n    |> sum()\n    |> group(columns: [\"hostname\"])\n    |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"per_process_disk_io_write_bytes\")\n    |> aggregateWindow(every: 30s, fn: last, createEmpty: false)\n    |> derivative(nonNegative: true)\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> group(columns: [\"hostname\", \"_time\"])\n    |> sum()\n    |> group(columns: [\"hostname\"])\n    |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Network Sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"network_io_bytes_sent\")\n    |> keep(columns: [\"_time\", \"_value\", \"hostname\"])\n    |> aggregateWindow(every: 30s, fn: last, createEmpty: false)\n    |> derivative(nonNegative: true)\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Network Recv",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"network_io_bytes_recv\")\n    |> keep(columns: [\"_time\", \"_value\", \"hostname\"])\n    |> aggregateWindow(every: 30s, fn: last, createEmpty: false)\n    |> derivative(nonNegative: true)\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "GPU Memory Usage",
   "type": "graph",
   "description": "Will be empty if GPU is not enabled",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"gpu_memory_used\")\n    |> group(columns: [\"hostname\", \"device_index\"])\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "description": "Will be empty if GPU is not enabled",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"gpu_utilization\")\n    |> group(columns: [\"hostname\", \"device_index\"])\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "GPU Power Draw %",
   "type": "graph",
   "description": "Will be empty if GPU is not enabled",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement =~ /gpu_power_(draw|limit)/)\n    |> aggregateWindow(every: v.windowPeriod, fn: mean)\n    |> sort(columns: [\"_time\"])\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\n    |> map(fn: (r) => ({ r with _value: r.gpu_power_draw / r.gpu_power_limit, _measurement: \"Power Draw %\" }))\n    |> keep(columns: [\"_time\", \"_value\", \"hostname\", \"device_index\"])"
    }
   ]
  },
  {
   "title": "CPU context switches",
   "type": "graph",
   "description": "Sum of voluntary and involuntary context switches",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] =~ /per_process_ctx_switches_(in)?voluntary/)\n    |> aggregateWindow(every: 30s, fn: last, createEmpty: false)\n    |> derivative(nonNegative: true)\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> group(columns: [\"hostname\", \"_time\"])\n    |> sum()\n    |> group(columns: [\"hostname\"])\n    |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "# Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"per_process_num_threads\")\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> group(columns: [\"hostname\", \"_time\"])\n    |> sum()\n    |> group(columns: [\"hostname\"])\n    |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "# File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"per_process_num_fds\")\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> group(columns: [\"hostname\", \"_time\"])\n    |> sum()\n    |> group(columns: [\"hostname\"])\n    |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Engine Job Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"run_engine_job\")\n    |> filter(fn: (r) => r[\"_field\"] == \"99.9_percentile\")\n    |> map(fn: (r) => ({\n        r with\n        _field: r.queue_name + \".\" + r.function\n    }))\n    |> drop(columns: [\"host\", \"metric_type\", \"queue_name\", \"function\", \"_measurement\"])"
    }
   ]
  },
  {
   "title": "All API Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"api_requests_all\")\n    |> map(fn: (r) => ({\n        _time: r._time,\n        _value: r._value,\n        _field: r.api_name + \": \" + r.method + \" \" + r.path + \" \" + r.status_code,\n    }))"
    }
   ]
  },
  {
   "title": "Running jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "started = from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"engine_job_state\" and r[\"state\"] == \"started\" and r[\"metric_type\"] == \"gauge\")\n    |> keep(columns: [\"state\", \"job_type\", \"_value\", \"_time\"])\n    |> group(columns: [\"job_type\"])\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n    |> fill(usePrevious: true)\n\n    finished = from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"engine_job_state\" and r[\"state\"] == \"finished\" and r[\"metric_type\"] == \"gauge\")\n    |> keep(columns: [\"state\", \"job_type\", \"_value\", \"_time\"])\n    |> group(columns: [\"job_type\"])\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n    |> fill(usePrevious: true)\n\n    join(tables:{started:started, finished:finished}, on:[\"_start\", \"_stop\", \"_time\", \"job_type\"])\n    |> group()\n    |> map(fn: (r) => ({\n        r with\n        _value: int(v: r._value_started - r._value_finished + 0.99)\n        }))\n    |> group(columns: [\"job_type\"])\n    |> yield()"
    }
   ]
  },
  {
   "title": "API 4xx Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"api_requests_4xx\")\n    |> map(fn: (r) => ({\n        _field: r.api_name + \": \" + r.method + \" \" + r.path + \" \" + r.status_code,\n        _time: r._time,\n        _value: r._value\n    }))"
    }
   ]
  },
  {
   "title": "Host Resource Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"mem\" and r[\"_field\"] == \"used_percent\")\n    |> map(fn: (r) => ({\n        r with\n        _field: \"mem_used\"\n        }))\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Number of Containers Running",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "import \"experimental/aggregate\"\nfrom(bucket: \"snorkel\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n\n|> filter(fn: (r) => r[\"_measurement\"] == \"memory_rss\")\n|> aggregate.rate(every: 2m, groupColumns: [\"machine\"],unit: 1s)\n|> group(columns: [\"_measurement\"])\n|> map(fn: (r) => ({\n    r with\n    _value: (r._value + 1.0) / (r._value + 1.0)\n    })\n)\n|> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n|> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Memory Usage (for alerting)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"mem\" and r[\"_field\"] == \"used_percent\")\n    |> map(fn: (r) => ({\n        r with\n        _field: \"mem_used\"\n        }))\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "5xx Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n\n    |> filter(fn: (r) => r[\"_measurement\"] == \"api_requests_5xx\")\n    |> map(fn: (r) => ({\n            _field: r.api_name + \": \" + r.method + \" \" + r.path + \" \" + r.status_code,\n            _time: r._time,\n            _value: r._value\n    }))"
    }
   ]
  },
  {
   "title": "Ongoing API requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "started = from(bucket: \"snorkel\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n\n|> filter(fn: (r) => r[\"_measurement\"] == \"request_started\")\n|> group(columns: [\"_time\", \"hostname\"])\n|> sum()\n|> group(columns: [\"hostname\"])\n|> aggregateWindow(every: v.windowPeriod, fn: last)\n|> fill(usePrevious: true)\n\n\nfinished = from(bucket: \"snorkel\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n\n|> filter(fn: (r) => r[\"_measurement\"] == \"request_finished\")\n|> group(columns: [\"_time\", \"hostname\"])\n|> sum()\n|> group(columns: [\"hostname\"])\n|> aggregateWindow(every: v.windowPeriod, fn: last)\n|> fill(usePrevious: true)\n\njoin(tables:{started:started, finished:finished}, on:[\"_time\", \"hostname\"])\n|> map(fn: (r) => ({\n        _time: r._time,\n        hostname: r.hostname,\n        _value: int(v: r._value_started - r._value_finished)\n}))"
    }
   ]
  },
  {
   "title": "Finished requests/min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n\n|> filter(fn: (r) => r[\"_measurement\"] == \"request_finished\")\n|> group(columns: [\"_time\", \"hostname\"])\n|> sum()\n|> group(columns: [\"hostname\"])\n|> derivative(unit: 1m, nonNegative: true)\n|> aggregateWindow(every: v.windowPeriod, fn: sum)"
    }
   ]
  }
 ]
}