{
 "title": "System Per-Process Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Per-process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"per_process_cpu_time\")\n    |> keep(columns: [\"_time\", \"_value\", \"hostname\", \"pid\"])\n    |> aggregateWindow(every: 30s, fn: last, createEmpty: false)\n    |> derivative(nonNegative: true)\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Per-process Memory RSS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"per_process_memory_rss\")\n    |> keep(columns: [\"_time\", \"_value\", \"hostname\", \"pid\"])\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Per-process Disk Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"per_process_disk_io_read_bytes\")\n    |> keep(columns: [\"_time\", \"_value\", \"hostname\", \"pid\"])\n    |> aggregateWindow(every: 30s, fn: last, createEmpty: false)\n    |> derivative(nonNegative: true)\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Per-process Disk Write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"snorkel\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"per_process_disk_io_write_bytes\")\n    |> keep(columns: [\"_time\", \"_value\", \"hostname\", \"pid\"])\n    |> aggregateWindow(every: 30s, fn: last, createEmpty: false)\n    |> derivative(nonNegative: true)\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}